export const POST_STATUS = Object.freeze({
  SOLD: 'SOLD',
  RESERVED: 'RESERVED',
  REJECTED: 'REJECTED',
  AVAILABLE: 'AVAILABLE',
  UNDER_REVIEW: 'UNDER REVIEW',
  AWAITING_DELETION: 'AWAITING DELETION'
})

export const ORDER_OPTION = Object.freeze({
  NEWEST: 'NEWEST',
  OLDEST: 'OLDEST',
  HIGHEST_PRICE: 'HIGHEST_PRICE',
  LOWEST_PRICE: 'LOWEST_PRICE'
})
