export const POST_STATUS = Object.freeze({
  SOLD: 'SOLD',
  RESERVED: 'RESERVED',
  REJECTED: 'REJECTED',
  AVAILABLE: 'AVAILABLE',
  UNDER_REVIEW: 'UNDER REVIEW',
  AWAITING_DELETION: 'AWAITING DELETION'
})
