export const SCREEN = Object.freeze({
  STARTER: 'StarterScreen',
  SIGNUP: 'SignUpScreen',
  SIGNIN: 'SignInScreen',
  HOME: 'HomeScreen',
  FORGOT_PASSWORD: 'ForgotPasswordScreen',
  ACTIVATE: 'ActivateScreen',
  RESET_PASSWORD: 'ResetPasswordScreen',
  CREATE_POST: 'CreatePostScreen',
  EDIT_POST: 'EditPostScreen',
  VIEW_POST: 'ViewPostScreen',
  PROFILE: 'ProfileScreen',
  EDIT_PROFILE: 'EditProfileScreen',
  USER_VIEW_POSTS: 'UserViewPostsScreen',
  WISHLIST: 'WishListScreen',
  BOOKING: 'BookingScreen',
  PURCHASE: 'PurchaseScreen',
  DETAILS: 'DetailsScreen',
  POSTS_MANAGE: 'PostManageScreen',
  POST_DETAIL: 'PostDetailScreen',
  ADMIN_HOME: 'AdminHomeScreen',
  BOOKING_MANAGE: 'BookingManageScreen',
  TRANSACTION_MANAGE: 'TransactionManageScreen',
  POSTS_MANAGE: 'PostsManageScreen',
  USERS_MANAGE: 'UsersManageScreen',
  DRAWER_FILTER: 'DrawerFilterScreen'
})
